version: "3.9"

services:
  backend:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  streamlit:
    build: .
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend
